data_root: data/raw
static_input_root: inputs_static
instance: "20.20.4"

constraints:
  Lw: 3600
  force_drone_ok: false

objective:
  mode: weighted
  lambda_w: 0.1
  drop_penalty: 2000.0
  weights:
    makespan: 0.5
    unserved: 0.5

features:
  mask: null

gp:
  pop_size: 200
  intermed_size: 100
  generations: 60
  max_depth: 4
  rm: 0.25
  rc: 0.8
  tournament_k: 3
  stall_gens: 15
  stall_eps: 1e-4
  seed: 42
  seed_ratio: 0.2
  seed_pairs:
    - ["min(TERM0, TERM4)", "min(TERM0, TERM4)"]
    - ["min(TERM0, TERM3)", "TERM3"]
    - ["TERM1", "TERM2"]
    - ["min(TERM1, TERM4)", "TERM3"]
    - ["max(TERM1, TERM5)", "min(TERM2, TERM4)"]
    - ["min(TERM1, TERM3)", "min(TERM1, TERM3)"]

log_dir: runs
